<?xml version="1.0" encoding="utf-8"?><Database Name="MCM_Keeper" Class="DbContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WAR-SQL100;Initial Catalog=MCM_Keeper;Integrated Security=True" SettingsObjectName="KeeperRichClient.Modules.Benefits.Properties.Settings" SettingsPropertyName="MCM_KeeperConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Healthcare.MedicalPacketTypes" Member="MedicalPacketTypes">
    <Type Name="MedicalPacketType">
      <Column Name="MedicalPacketID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MedicalPacketName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="MedicalPacketType_MedicalPacketTypeSetting" Member="MedicalPacketTypeSettings" ThisKey="MedicalPacketID" OtherKey="MedicalPacketID" Type="MedicalPacketTypeSetting" />
      <Association Name="MedicalPacketType_ConfiguredMedicalPacketToEmployee" Member="ConfiguredMedicalPacketToEmployees" ThisKey="MedicalPacketID" OtherKey="MedicalPacketTypeID" Type="ConfiguredMedicalPacketToEmployee" />
    </Type>
  </Table>
  <Table Name="Healthcare.MedicalPacketTypeSettings" Member="MedicalPacketTypeSettings">
    <Type Name="MedicalPacketTypeSetting">
      <Column Name="MedicalPacketID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MedicalPacketTotalCost" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="OccupationalMedicinePartPC" Type="System.Decimal" DbType="Decimal(10,10) NOT NULL" CanBeNull="false" />
      <Column Name="PreventionMedicinePartPC" Type="System.Decimal" DbType="Decimal(10,10) NOT NULL" CanBeNull="false" />
      <Column Name="IndividualMedicinePartPC" Type="System.Decimal" DbType="Decimal(10,10) NOT NULL" CanBeNull="false" />
      <Column Name="FamilyMedicinePartPC" Type="System.Decimal" DbType="Decimal(10,10) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DeactivateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MedicalPacketType_MedicalPacketTypeSetting" Member="MedicalPacketType" ThisKey="MedicalPacketID" OtherKey="MedicalPacketID" Type="MedicalPacketType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Benefits.BeneficiaryGroupDetails" Member="BeneficiaryGroupDetails">
    <Type Name="BeneficiaryGroupDetail">
      <Column Name="BeneficiaryGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryAddDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryRemoveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BeneficiaryGroupId_BeneficiaryGroupDetail" Member="BeneficiaryGroupId1" ThisKey="BeneficiaryGroupID" OtherKey="GroupID" Type="BeneficiaryGroupId" IsForeignKey="true" />
      <Association Name="Beneficiary_BeneficiaryGroupDetail" Member="Beneficiary" ThisKey="BeneficiaryID" OtherKey="BeneficiaryID" Type="Beneficiary" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Benefits.BeneficiaryGroupIds" Member="BeneficiaryGroupIds">
    <Type Name="BeneficiaryGroupId">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="BeneficiaryGroupId_BeneficiaryGroupDetail" Member="BeneficiaryGroupDetails" ThisKey="GroupID" OtherKey="BeneficiaryGroupID" Type="BeneficiaryGroupDetail" />
      <Association Name="BeneficiaryGroupId_ConfiguredMedicalPacketToEmployee" Member="ConfiguredMedicalPacketToEmployees" ThisKey="GroupID" OtherKey="BeneficiaryGroupID" Type="ConfiguredMedicalPacketToEmployee" />
    </Type>
  </Table>
  <Table Name="Healthcare.ConfiguredMedicalPacketToEmployee" Member="ConfiguredMedicalPacketToEmployees">
    <Type Name="ConfiguredMedicalPacketToEmployee">
      <Column Name="ConfiguredMedicalPacketID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MedicalPacketTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValidFrom" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ValidTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IncludedInLimit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPayedByEmployee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AssignDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TakingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TakingReasonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="BeneficiaryGroupId_ConfiguredMedicalPacketToEmployee" Member="BeneficiaryGroupId1" ThisKey="BeneficiaryGroupID" OtherKey="GroupID" Type="BeneficiaryGroupId" IsForeignKey="true" />
      <Association Name="MedicalPacketType_ConfiguredMedicalPacketToEmployee" Member="MedicalPacketType" ThisKey="MedicalPacketTypeID" OtherKey="MedicalPacketID" Type="MedicalPacketType" IsForeignKey="true" />
      <Association Name="TakingReasonType_ConfiguredMedicalPacketToEmployee" Member="TakingReasonType" ThisKey="TakingReasonID" OtherKey="TakingReasonID" Type="TakingReasonType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Benefits.ConfiguredMultisportPacketsToEmployees" Member="ConfiguredMultisportPacketsToEmployees">
    <Type Name="ConfiguredMultisportPacketsToEmployee">
      <Column Name="ConfiguredBenefitPacketID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MultiSportPacketTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValidFrom" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ValidTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsIncludedInLimit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPayedByEmployee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AssignDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TakingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TakingReasonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="MultisportPacketType_ConfiguredMultisportPacketsToEmployee" Member="MultisportPacketType" ThisKey="MultiSportPacketTypeID" OtherKey="MultisportPacketTypeID" Type="MultisportPacketType" IsForeignKey="true" />
      <Association Name="TakingReasonType_ConfiguredMultisportPacketsToEmployee" Member="TakingReasonType" ThisKey="TakingReasonID" OtherKey="TakingReasonID" Type="TakingReasonType" IsForeignKey="true" />
      <Association Name="Beneficiary_ConfiguredMultisportPacketsToEmployee" Member="Beneficiary" ThisKey="BeneficiaryID" OtherKey="BeneficiaryID" Type="Beneficiary" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Parkings.ParkingPlaces" Member="ParkingPlaces">
    <Type Name="ParkingPlace">
      <Column Name="ParkingPlaceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParkingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParkingPlaceName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ParkingPlace_ParkingPlacesToEmployee" Member="ParkingPlacesToEmployees" ThisKey="ParkingPlaceID" OtherKey="ParkingPlaceID" Type="ParkingPlacesToEmployee" />
      <Association Name="Parking_ParkingPlace" Member="Parking" ThisKey="ParkingID" OtherKey="ParkingID" Type="Parking" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Parkings.ParkingPlacesToEmployees" Member="ParkingPlacesToEmployees">
    <Type Name="ParkingPlacesToEmployee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParkingPlaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsIncludedInLimit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AssignDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TakingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TakingReasonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="ParkingPlace_ParkingPlacesToEmployee" Member="ParkingPlace" ThisKey="ParkingPlaceID" OtherKey="ParkingPlaceID" Type="ParkingPlace" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Parkings.Parkings" Member="Parkings">
    <Type Name="Parking">
      <Column Name="ParkingID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParkingName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParkingCost" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Parking_ParkingPlace" Member="ParkingPlaces" ThisKey="ParkingID" OtherKey="ParkingID" Type="ParkingPlace" />
    </Type>
  </Table>
  <Table Name="Benefits.MultisportPacketTypes" Member="MultisportPacketTypes">
    <Type Name="MultisportPacketType">
      <Column Name="MultisportPacketTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MultisportPacketTypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MultisportPacketTypeCost" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MultisportPacketType_ConfiguredMultisportPacketsToEmployee" Member="ConfiguredMultisportPacketsToEmployees" ThisKey="MultisportPacketTypeID" OtherKey="MultiSportPacketTypeID" Type="ConfiguredMultisportPacketsToEmployee" />
    </Type>
  </Table>
  <Table Name="General.TakingReasonTypes" Member="TakingReasonTypes">
    <Type Name="TakingReasonType">
      <Column Name="TakingReasonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TakingReasonName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TakingReasonType_ConfiguredMedicalPacketToEmployee" Member="ConfiguredMedicalPacketToEmployees" ThisKey="TakingReasonID" OtherKey="TakingReasonID" Type="ConfiguredMedicalPacketToEmployee" />
      <Association Name="TakingReasonType_ConfiguredMultisportPacketsToEmployee" Member="ConfiguredMultisportPacketsToEmployees" ThisKey="TakingReasonID" OtherKey="TakingReasonID" Type="ConfiguredMultisportPacketsToEmployee" />
    </Type>
  </Table>
  <Table Name="Benefits.Beneficiaries" Member="Beneficiaries">
    <Type Name="Beneficiary">
      <Column Name="BeneficiaryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BeneficiaryFName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryLName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryPesel" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryBirthDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryCitizenship" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiarySex" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryPhoneNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryEmailAddress" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryParentEmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Beneficiary_BeneficiaryGroupDetail" Member="BeneficiaryGroupDetails" ThisKey="BeneficiaryID" OtherKey="BeneficiaryID" Type="BeneficiaryGroupDetail" />
      <Association Name="Beneficiary_ConfiguredMultisportPacketsToEmployee" Member="ConfiguredMultisportPacketsToEmployees" ThisKey="BeneficiaryID" OtherKey="BeneficiaryID" Type="ConfiguredMultisportPacketsToEmployee" />
    </Type>
  </Table>
  <Table Name="LanguageCourses.LanguageCourseInstructors" Member="LanguageCourseInstructors">
    <Type Name="LanguageCourseInstructor">
      <Column Name="InstructorId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InstructorFName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="InstructorLName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="LanguageCourseInstructor_InstructorsToLanguageCourse" Member="InstructorsToLanguageCourses" ThisKey="InstructorId" OtherKey="LanguageCourseInstructorId" Type="InstructorsToLanguageCourse" />
    </Type>
  </Table>
  <Table Name="LanguageCourses.LanguageCourses" Member="LanguageCourses">
    <Type Name="LanguageCourse">
      <Column Name="LanguageCourseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LanguageCourseName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LanguageCourseCost" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="LanguageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LanguageCourse_LanguageCoursesToEmployee" Member="LanguageCoursesToEmployees" ThisKey="LanguageCourseID" OtherKey="LanguageCourseID" Type="LanguageCoursesToEmployee" />
      <Association Name="LanguagesForCourse_LanguageCourse" Member="LanguagesForCourse" ThisKey="LanguageID" OtherKey="LanguageID" Type="LanguagesForCourse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="LanguageCourses.LanguagesForCourses" Member="LanguagesForCourses">
    <Type Name="LanguagesForCourse">
      <Column Name="LanguageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LanguageName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="LanguagesForCourse_LanguageCourse" Member="LanguageCourses" ThisKey="LanguageID" OtherKey="LanguageID" Type="LanguageCourse" />
    </Type>
  </Table>
  <Table Name="LanguageCourses.LanguageCoursesToEmployees" Member="LanguageCoursesToEmployees">
    <Type Name="LanguageCoursesToEmployee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LanguageCourseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsIncludedInLimit" Type="System.Int32" DbType="Int NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TakingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TakingReasonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="LanguageCoursesToEmployee_InstructorsToLanguageCourse" Member="InstructorsToLanguageCourses" ThisKey="Id" OtherKey="LanguageCourseToEmpId" Type="InstructorsToLanguageCourse" />
      <Association Name="LanguageCourse_LanguageCoursesToEmployee" Member="LanguageCourse" ThisKey="LanguageCourseID" OtherKey="LanguageCourseID" Type="LanguageCourse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="LanguageCourses.InstructorsToLanguageCourses" Member="InstructorsToLanguageCourses">
    <Type Name="InstructorsToLanguageCourse">
      <Column Name="LanguageCourseToEmpId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LanguageCourseInstructorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InstructorAssignDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InstructorTakingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="LanguageCourseInstructor_InstructorsToLanguageCourse" Member="LanguageCourseInstructor" ThisKey="LanguageCourseInstructorId" OtherKey="InstructorId" Type="LanguageCourseInstructor" IsForeignKey="true" />
      <Association Name="LanguageCoursesToEmployee_InstructorsToLanguageCourse" Member="LanguageCoursesToEmployee" ThisKey="LanguageCourseToEmpId" OtherKey="Id" Type="LanguageCoursesToEmployee" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="Benefits.spAddBeneficiaryToMedicalPacket" Method="spAddBeneficiaryToMedicalPacket">
    <Parameter Name="BeneficiaryID" Parameter="beneficiaryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MedicalPacketID" Parameter="medicalPacketID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Benefits.spRemoveBeneficiaryFromMedicalPacket" Method="spRemoveBeneficiaryFromMedicalPacket">
    <Parameter Name="BeneficiaryID" Parameter="beneficiaryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MedicalPacketId" Parameter="medicalPacketId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Healthcare.spAddMedicalPacketToEmployee" Method="spAddMedicalPacketToEmployee">
    <Parameter Name="EmployeeId" Parameter="employeeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="MedicalPacketTypeId" Parameter="medicalPacketTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BeneficiaryGroupId" Parameter="beneficiaryGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValidFrom" Parameter="validFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ValidTo" Parameter="validTo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IncludedInLimit" Parameter="includedInLimit" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsPayedByEmployee" Parameter="isPayedByEmployee" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Note" Parameter="note" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Healthcare.spCreateBeneficiaryGroupForMedPack" Method="spCreateBeneficiaryGroupForMedPack">
    <Parameter Name="MedPackID" Parameter="medPackID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Benefits.fMultisportCardTypes" Method="fMultisportCardTypes" IsComposable="true">
    <ElementType Name="fMultisportCardTypesResult">
      <Column Name="MultisportPacketTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MultisportPacketTypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MultisportPacketTypeCost" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Parkings.fParksWithFreePlaces" Method="fParksWithFreePlaces" IsComposable="true">
    <ElementType Name="fParksWithFreePlacesResult">
      <Column Name="ParkingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParkingName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParkingCost" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Parkings.spTakeParkingPlace" Method="spTakeParkingPlace">
    <Parameter Name="EmployeeId" Parameter="employeeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParkingPlaceId" Parameter="parkingPlaceId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Parkings.spSaveParkingPlace" Method="spSaveParkingPlace">
    <Parameter Name="EmployeeId" Parameter="employeeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParkingPlaceId" Parameter="parkingPlaceId" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsIncludedInLimit" Parameter="isIncludedInLimit" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="MultiSport.spAddConfigutedMultiSportCard" Method="spAddConfigutedMultiSportCard">
    <Parameter Name="CardTypeId" Parameter="cardTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="EmployeeId" Parameter="employeeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BeneficiaryId" Parameter="beneficiaryId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValidFrom" Parameter="validFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ValidTo" Parameter="validTo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IsIncludedInLimit" Parameter="isIncludedInLimit" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsPayedByEmployee" Parameter="isPayedByEmployee" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Benefits.fMultisportOwnerToEmployee" Method="fMultisportOwnerToEmployee" IsComposable="true">
    <Parameter Name="EmployeeId" Parameter="employeeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="fMultisportOwnerToEmployeeResult">
      <Column Name="ConfiguredBenefitPacketID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MultisportPacketTypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryFName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BeneficiaryLName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="MultiSport.spTakeConfiguredMultiSportCard" Method="spTakeConfiguredMultiSportCard">
    <Parameter Name="ConfiguredMultiSportCardId" Parameter="configuredMultiSportCardId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Healthcare.spRemoveMedicalPacketFromEmployee" Method="spRemoveMedicalPacketFromEmployee">
    <Parameter Name="MedicalPacketId" Parameter="medicalPacketId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TakingDate" Parameter="takingDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TakingReasonId" Parameter="takingReasonId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Note" Parameter="note" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fBeneficiariesToEmployee" Method="fBeneficiariesToEmployee" IsComposable="true">
    <Parameter Name="ParentEmployeeId" Parameter="parentEmployeeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="fBeneficiariesToEmployeeResult">
      <Column Name="BeneficiaryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryFName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryLName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryPesel" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryBirthDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryCitizenship" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiarySex" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryPhoneNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryEmailAddress" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryParentEmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Benefits.spCreateMedicalBeneficiary" Method="spCreateMedicalBeneficiary">
    <Parameter Name="BeneficiaryFName" Parameter="beneficiaryFName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="BeneficiaryLName" Parameter="beneficiaryLName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="BeneficiaryPesel" Parameter="beneficiaryPesel" Type="System.String" DbType="NVarChar(11)" />
    <Parameter Name="BeneficiaryBirthDate" Parameter="beneficiaryBirthDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="BeneficiaryCitizenship" Parameter="beneficiaryCitizenship" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="BeneficiarySex" Parameter="beneficiarySex" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="BeneficiaryPhoneNumber" Parameter="beneficiaryPhoneNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BeneficiaryEmailAddress" Parameter="beneficiaryEmailAddress" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="BeneficiaryParentEmployeeId" Parameter="beneficiaryParentEmployeeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Benefits.spCreateMultisportBeneficiary" Method="spCreateMultisportBeneficiary">
    <Parameter Name="BeneficiaryFName" Parameter="beneficiaryFName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="BeneficiaryLName" Parameter="beneficiaryLName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="BeneficiaryParentEmployeeId" Parameter="beneficiaryParentEmployeeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Healthcare.vBeneficiaries2MedPack" Method="vBeneficiaries2MedPack" IsComposable="true">
    <Parameter Name="MedPackID" Parameter="medPackID" Type="System.Int32" DbType="Int" />
    <ElementType Name="vBeneficiaries2MedPackResult">
      <Column Name="BeneficiaryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryFName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BeneficiaryLName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AssignDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="LanguageCourses.spAddInstructorToCourse" Method="spAddInstructorToCourse">
    <Parameter Name="CourseId" Parameter="courseId" Type="System.Int32" DbType="Int" />
    <Parameter Name="InstructorId" Parameter="instructorId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="LanguageCourses.spRemoveInstructorFromCourse" Method="spRemoveInstructorFromCourse">
    <Parameter Name="CourseId" Parameter="courseId" Type="System.Int32" DbType="Int" />
    <Parameter Name="InstructorId" Parameter="instructorId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Healthcare.vMedicalPacketsToEmployee" Method="vMedicalPacketsToEmployee" IsComposable="true">
    <Parameter Name="EmployeeId" Parameter="employeeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="vMedicalPacketsToEmployeeResult">
      <Column Name="ConfiguredMedicalPacketID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MedicalPacketTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ValidFrom" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ValidTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsIncludedInLimit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPayedByEmployee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AssignDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TakingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TakingReasonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MedicalPacketName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="LanguageCourses.spAddNewLanguageCourse" Method="spAddNewLanguageCourse">
    <Parameter Name="LanguageCourseId" Parameter="languageCourseId" Type="System.Int32" DbType="Int" />
    <Parameter Name="EmployeeId" Parameter="employeeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="LanguageCourses.spModifyLangCourseEndDate" Method="spModifyLangCourseEndDate">
    <Parameter Name="LanguageCourseId" Parameter="languageCourseId" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewLangCourseEndDate" Parameter="newLangCourseEndDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
</Database>