//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace Tests
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class BeneficiaryGroupId
//    {
//        public BeneficiaryGroupId()
//        {
//            this.BeneficiaryGroupDetails = new HashSet<BeneficiaryGroupDetails>();
//            this.ConfiguredMedicalPacket = new HashSet<ConfiguredMedicalPacket>();
//        }
    
//        public int BeneficiaryGroupID1 { get; set; }
//        public bool IsActive { get; set; }
    
//        public virtual ICollection<BeneficiaryGroupDetails> BeneficiaryGroupDetails { get; set; }
//        public virtual ICollection<ConfiguredMedicalPacket> ConfiguredMedicalPacket { get; set; }
//    }
//}
