//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryGroupDetails
    {
        public int BeneficiaryGroupID { get; set; }
        public int BeneficiaryID { get; set; }
        public System.DateTime BeneficiaryAddDate { get; set; }
        public Nullable<System.DateTime> BeneficiaryRemoveDate { get; set; }
    
        public virtual Beneficiaries Beneficiaries { get; set; }
        public virtual BeneficiaryGroupId BeneficiaryGroupId1 { get; set; }
    }
}
