//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiaries
    {
        public Beneficiaries()
        {
            this.BeneficiaryGroupDetails = new HashSet<BeneficiaryGroupDetails>();
        }
    
        public int BeneficiaryID { get; set; }
        public string BeneficiaryFName { get; set; }
        public string BeneficiaryLName { get; set; }
        public string BeneficiaryPesel { get; set; }
        public string BeneficiaryAddress { get; set; }
        public int BeneficiaryIdentityCardType { get; set; }
        public string BeneficiaryIdentityCardNumber { get; set; }
        public int BeneficiaryParentEmployeeID { get; set; }
    
        public virtual ICollection<BeneficiaryGroupDetails> BeneficiaryGroupDetails { get; set; }
        public virtual IdentityCardTypes IdentityCardTypes { get; set; }
    }
}
