//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class McmKeeper : DbContext
    {
        public McmKeeper()
            : base("name=McmKeeper")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficiaries> Beneficiaries { get; set; }
        public virtual DbSet<BeneficiaryGroupId> BeneficiaryGroupId { get; set; }
        public virtual DbSet<ConfiguredMedicalPacket> ConfiguredMedicalPacket { get; set; }
        public virtual DbSet<MedicalPacketTypes> MedicalPacketTypes { get; set; }
        public virtual DbSet<BeneficiaryGroupDetails> BeneficiaryGroupDetails { get; set; }
        public virtual DbSet<ConfiguredMedicalPacketToEmployee> ConfiguredMedicalPacketToEmployee { get; set; }
        public virtual DbSet<MedicalPacketTypeSettings> MedicalPacketTypeSettings { get; set; }
        public virtual DbSet<IdentityCardTypes> IdentityCardTypes { get; set; }
    
        public virtual ObjectResult<GetEmployees_Result> GetEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployees_Result>("GetEmployees");
        }
    }
}
