//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguredMedicalPacketToEmployee
    {
        public int ConfiguredMedicalPacketID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime AssignDate { get; set; }
        public bool IncludedInLimit { get; set; }
        public string IsPayedByEmployee { get; set; }
        public Nullable<System.DateTime> TakingDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> TakingReasonID { get; set; }
    
        public virtual ConfiguredMedicalPacket ConfiguredMedicalPacket { get; set; }
    }
}
