//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityCardTypes
    {
        public IdentityCardTypes()
        {
            this.Beneficiaries = new HashSet<Beneficiaries>();
        }
    
        public int IdentityCardTypeID { get; set; }
        public string IdentityCardTypeName { get; set; }
    
        public virtual ICollection<Beneficiaries> Beneficiaries { get; set; }
    }
}
