//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalPacketTypeSettings
    {
        public int MedicalPacketID { get; set; }
        public decimal MedicalPacketTotalCost { get; set; }
        public decimal OccupationalMedicinePartPC { get; set; }
        public decimal PreventionMedicinePartPC { get; set; }
        public decimal IndividualMedicinePartPC { get; set; }
        public decimal FamilyMedicinePartPC { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DeactivateDate { get; set; }
    
        public virtual MedicalPacketTypes MedicalPacketTypes { get; set; }
    }
}
