#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperRichClient.Modules.Employees.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MCM_Keeper")]
	public partial class EmployeeLINQClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EmployeeLINQClassDataContext() : 
				base(global::KeeperRichClient.Modules.Employees.Properties.Settings.Default.MCM_KeeperConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeLINQClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeLINQClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeLINQClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeLINQClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Interface.GetEmployees")]
		public ISingleResult<GetEmployeesResult> GetEmployees()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetEmployeesResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetEmployeesResult
	{
		
		private int _EmpId;
		
		private string _EmpFName;
		
		private string _EmpLName;
		
		private string _EmpEmail;
		
		private System.Nullable<int> _EmpLvlId;
		
		public GetEmployeesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpId", DbType="Int NOT NULL")]
		public int EmpId
		{
			get
			{
				return this._EmpId;
			}
			set
			{
				if ((this._EmpId != value))
				{
					this._EmpId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpFName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EmpFName
		{
			get
			{
				return this._EmpFName;
			}
			set
			{
				if ((this._EmpFName != value))
				{
					this._EmpFName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpLName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EmpLName
		{
			get
			{
				return this._EmpLName;
			}
			set
			{
				if ((this._EmpLName != value))
				{
					this._EmpLName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpEmail", DbType="NVarChar(200)")]
		public string EmpEmail
		{
			get
			{
				return this._EmpEmail;
			}
			set
			{
				if ((this._EmpEmail != value))
				{
					this._EmpEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpLvlId", DbType="Int")]
		public System.Nullable<int> EmpLvlId
		{
			get
			{
				return this._EmpLvlId;
			}
			set
			{
				if ((this._EmpLvlId != value))
				{
					this._EmpLvlId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
